markdown: kramdown
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
highlighter: rouge
collections:
    talks:
        output: true
        default:
            layout: talk
